### ISSUE TITLE
Correlation between frame_positions in global_pose and ego_orient in Comma log

### ISSUE THREAD

**Issue by didpurwanto** [OpenPerceptionX/Openpilot-Deepdive#11]
Great implementation to learn OpenPilot. I was wondering about two thing:
1. Is the frame_positions in global_pose input data is equal to ego_pose in comma log in [modelDataV2 struct](https://github.com/commaai/cereal/blob/fbd45de6e6bc71b4561eaef65dd86fce952c5d55/log.capnp#L723). Similar case with frame_orientations with ego_orient.
2. One of the sub-models of OpenPIlot in Prediction head is 'POSE'. Is it related to global_pose in comma2k19 dataset? or is it ego_pose?

Thanks

**Comment by ElectronicElephant** [comment]
Hi,

First, sorry for the late reply because I was on vacation these days.

Second, I'm sorry that I am not quite familiar with Openpilot's C++ code, but I can tell you that, in my implementation, `frame_positions` and `frame_orientations` stand for the **relative** ego pos and ori of each frame. They're **relative to the first frame**.

I am not sure about your second question. I can not answer it.

Feel free to reach me if you have further questions.

**Comment by yang-Michael** [comment]
> 

Hi, thx your excellent work! But now i meet some problem about coordinate transform in my own data.
![image](https://user-images.githubusercontent.com/29976881/189803397-5a56e8f3-c3b3-4867-b469-911bf25caf29.png)
The picture above is the data format of comma2k19 that annotate the frame_orientations: global orientations as quaternion needed to rotate from ECEF  frame to local camera frame defined as [forward, right, down] (hamilton quaternion!!!!)，but you explain that the gt trajectory is in ego vehicle's coordinate system in the paper below.
![image](https://user-images.githubusercontent.com/29976881/189803658-8a03b4fd-963f-4668-bd46-cb84a3d87ad0.png)

So now, i'm confused for the coordinate transform, because i have no idea about how to transform coodinates corectlly?
Can you explain the question and tell me the relevant code in your github?
I'm looking forward to your reply! Thx agian!

**Comment by ElectronicElephant** [comment]
Hi @yang-Michael ,

All datasets like comma2k19 have to use the static, earth coordinate (a.k.a. global corrdinate). However, in many deep-learning models, the coordinate system must be the dynamic ego-based systems.

We don't predict orientations here, so we only care about translations. (But basically, you can treat them in the same way in terms of coordinate transformation.) 

The transform to make global coordinates to ego is here:
https://github.com/OpenPerceptionX/Openpilot-Deepdive/blob/a3a31921286a66612834ce66e2b29739bf80b783/data.py#L277

First, we minus the global positions in the future by the current global position. Then, we rotate them according to the current orientation.

I know that your situation may be a bit different, but the big picture is the same.

**Comment by yang-Michael** [comment]
> Hi @yang-Michael ,
> 
> All datasets like comma2k19 have to use the static, earth coordinate (a.k.a. global corrdinate). However, in many deep-learning models, the coordinate system must be the dynamic ego-based systems.
> 
> We don't predict orientations here, so we only care about translations. (But basically, you can treat them in the same way in terms of coordinate transformation.)
> 
> The transform to make global coordinates to ego is here:
> 
> https://github.com/OpenPerceptionX/Openpilot-Deepdive/blob/a3a31921286a66612834ce66e2b29739bf80b783/data.py#L277
> 
> First, we minus the global positions in the future by the current global position. Then, we rotate them according to the current orientation.
> 
> I know that your situation may be a bit different, but the big picture is the same.

hi@ElectronicElephant, 
thx for your reply, and i understand what u say. But it's also some problems:
1、I had been used the transform to make global coordinates to ego, but what i want to figure out is that why i can't align the gt path with origin image in my own data? As shown in picture below.(the height maybe mistake and the Perspective Transformation also is)
![image](https://user-images.githubusercontent.com/29976881/189826317-1c670a59-5ec1-498f-997f-ad2d8061abf8.png)

[https://github.com/OpenPerceptionX/Openpilot-Deepdive/blob/main/data.py#L277](url)
2、More than that, i find that the same transform relationship from ecef to local cause the diffirent result( for the same vehicle but data collected at different times on the same day )
![image](https://user-images.githubusercontent.com/29976881/189830466-b2b9f931-4aa8-4bba-bad5-24180d1f7ae3.png)

![image](https://user-images.githubusercontent.com/29976881/189831281-3d706a5b-4dd0-4c56-9272-1ef47b328bbd.png)

Can y give me some suggestion?

**Comment by ElectronicElephant** [comment]
Hi @yang-Michael 

我建议先从数据集里面抽一些样本出来，直接用 demo.py 观察轨迹是否正常。一定要先把右侧的鸟瞰图弄对。

至于投影回原图，那需要非常准确的相机内外参。大概率是内外参有误。

---

I believe it's easier to make the BEV visualization (on the right side) correct. Then, check camera intrinsic and extrinsic params. If they're correct, then projection (on the left side) should work too.

**Comment by yang-Michael** [comment]
> 

好的，非常感谢！

**Comment by yang-Michael** [comment]
https://github.com/OpenPerceptionX/Openpilot-Deepdive/blob/a3a31921286a66612834ce66e2b29739bf80b783/utils_comma2k19/coordinates.py#L74
还有个问题，你这里给出的一个case是从地理坐标系转local的，那么这个init_ecef是如何选择的呢？我觉得我的问题出在这里了，我自己转的时候没有用到这个init_ecef，而是直接用了ned2ecef_matrix这个旋转矩阵，这个对结果会影响吗？
