### ISSUE TITLE
Dataset splits: Comma2k19

### ISSUE THREAD

**Issue by ElectronicElephant** [OpenPerceptionX/Openpilot-Deepdive#4]
We release the dataset splits of Comma2k19 we used.

The current code is adapted to Comma2k19 dataset. Therefore, we recommend using it over nuScenes.

[comma2k19_train_non_overlap.txt](https://github.com/OpenPerceptionX/Openpilot-Deepdive/files/8945538/comma2k19_train_non_overlap.txt)
[comma2k19_val_non_overlap.txt](https://github.com/OpenPerceptionX/Openpilot-Deepdive/files/8945539/comma2k19_val_non_overlap.txt)

**Comment by nathanoy** [comment]
Since the repo moved, the new links are:

[omma2k19_train_non_overlap.txt](https://github.com/OpenDriveLab/Openpilot-Deepdive/files/8945538/comma2k19_train_non_overlap.txt)
[comma2k19_val_non_overlap.txt](https://github.com/OpenDriveLab/Openpilot-Deepdive/files/8945539/comma2k19_val_non_overlap.txt)
